# Title shown in Application Information tab.
title: Cloud Engineering Main
# Sub Title shown in Application Information tab.
description: Create all of the compartments, basic dynamic groups, and policies needed to have a cloud-engineering structure inside the tenancy.
informationalText: Groups and Dynamic Groups will be located inside of the non-default Identity Domain.
schemaVersion: 1.1.0
version: "20190304"

locale: "en"
variableGroups:
  - title: "Identity Domain Configuration"
    variables:
      - home_region
      - domain_id
  - title: "Compartment Configuration"
    variables:
      - engineer_compartment_base_name
  - title: "Group Configuration"
    variables:
      - engineer_group_name
      - engineer_oac_group_name
      - engineer_datascience_group_name
      - engineer_mysql_group_name
      - exacs_admin_group_name
  - title: "Services" 
    variables: 
      - create_oic
      - create_oda
      - create_ai
      - create_ds
      - create_exa
      - create_oac
      - create_func
      - create_mysql
  - title: "Hidden Variables" 
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key_path
      - region
      - private_key_password

variables:
  # string field
  engineer_compartment_base_name:
    type: string
    minLength: 1
    maxLength: 30
    # pattern: "^[a-z][a-zA-Z0-9]+$"
    # title is used as the label if present
    title: Compartment Name
    # description used as the tooltip if present
    description: Name of the main compartment for all cloud engineers to have a compartment inside of.  The base name here will also get a "-shared" compartment.
    default: cloud-engineering
    required: true

  ce_domain_id:
    title: Identity Domain OCID
    type: string
    description: Already created Identity Domain for cloud engineers.

  default_domain_id:
    title: Identity Domain OCID
    type: string
    description: Default Identity Domain for tenancy.

  engineer_group_name:
    title: Name of IAM group for engineers
    type: string
    description: Change as necessary
    default: cloud-engineering-domain-users

  engineer_datascience_group_name:
    title: Name of IAM group for Data Science engineers
    type: string
    description: Change as necessary
    default: cloud-engineering-datascience-users

  engineer_oac_group_name:
    title: Name of IAM group for Oracle Analytics Admins
    type: string
    description: Change as necessary
    default: cloud-engineering-oacadmin-users

  engineer_mysql_group_name:
    title: Name of IAM group for MySQL Heatwave engineers
    type: string
    description: Change as necessary
    default: cloud-engineering-mysql-users

  exacs_admin_group_name:
    title: Name of IAM group for ExaCS Admins
    type: string
    description: Change as necessary
    default: cloud-engineering-exacs-admins

  create_oic:
    title: Create the OIC Policy and compartment
    type: boolean
  create_exa:
    title: Create the ExaCS Policy and compartment
    type: boolean
  create_oda:
    title: Create the ODA Policy and compartment
    type: boolean
  create_mysql:
    title: Create the MySQL Policy and compartment
    type: boolean
  create_oac:
    title: Create the OAC Policy and compartment
    type: boolean
  create_ds:
    title: Create the Data Science Policy and compartment
    type: boolean
  create_ai:
    title: Create the AI and GenAI Policy
    type: boolean
  create_gg:
    title: Create the GoldenGate Policy and compartment
    type: boolean
  create_func:
    title: Create the OOCI Functions Policy
    type: boolean

