# Title shown in Application Information tab.
title: Shared VCN
# Sub Title shown in Application Information tab.
description: Creates a basic VCN
informationalText: In development as of 3/3/2025
schemaVersion: 1.1.0

locale: "en"
variableGroups:
  - title: "Basic Information" 
    variables:
      - compartment_ocid
      - vcn_name
      - vcn_cidr_blocks
      - subnet_names
      - subnet_cidr_blocks

  - title: "DRG"
    variables:
      - is_attach_drg
      - drg_ocid

  - title: "Hidden Variables" 
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key_path
      - region
      - private_key_password

variables:
  # string field
  compartment_ocid:
    type: oci:identity:compartment:id
    title: Compartment OCID
    # description used as the tooltip if present
    description: Compartment where this VCN will get created
    required: true

  vcn_name:
    type: string
    title: Base name of VCN
    description: The name, to which everything will append.  IE cloud-engineering-shared
    required: true
    default: "cloud-engineering-shared-"

  vcn_cidr_block:
    type: string
    title: VCN CIDR Block
    description: CIDR Block, ie 10.0.0.0/24
    required: true
    default: "172.17.99.0/24"

  subnet_names:
    type: array
    title: Subnet Names
    description: Subnet names (appended to base)
    required: true
    default: [web,app]
    
  subnet_types:
    type: array
    title: Subnet Types
    description: Subnet types (determines routing)
    required: true
    default: [public,private]
    
  subnet_cidr_blocks:
    type: array
    title: VCN CIDR Block
    description: CIDR Block, ie 10.0.0.0/24
    required: true
    default: [172.17.99.0/25,172.17.99.128/25]
  
  is_attach_drg:
    type: boolean
    title: Attach to DRG?
    description: Whether to attach to DRG

  drg_ocid:
    type: string
    description: Valid DRG OCID
    required: false
    visible: is_attach_drg
    default: null
